#define FORCE_ALIGN

#define HAVE_POSIX_MEMALIGN
#define HAVE_OBOE
#define HAVE_DLFCN_H
#define HAVE_MALLOC_H
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SETNAME_NP
#define HAVE_NEON
#define HAVE_GETOPT

#define ALSOFT_EMBED_HRTF_DATA